version: '3'

services:
  gogs-git:
    image: gogs/gogs
    depends_on:
      - gogs-db    
    ports:
    - "22:22"
    - "80:3000"
    volumes:
      - "/opt/gogs-git/data:/data"
      - "/opt/gogs-git/templates:/app/gogs/templates"
    restart: always
    networks:
    - gogs-git
    deploy:
      placement:
        constraints: [node.role == manager]

  gogs-db:
    image: sameersbn/postgresql
    ports:
    - "5432:5432"
    restart: always
    volumes:
      - "/opt/gogs-git/db:/var/lib/postgresql"
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    networks:
    - gogs-git
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  gogs-git:
    external:
      name: git