version: '3'

services:
  gogs-git:
    image: gogs/gogs
    depends_on:
      - gogs-db    
    ports:
    - "22:22"
    - "80:3000"
    volumes:
      - type: bind
        source: /opt/gogs-git/data
        target: /data
      - type: bind
        source: /opt/gogs-git/templates
        target: /app/gogs/templates
    restart: always
    networks:
    - git
    deploy:
      placement:
        constraints: [node.role == manager]

  gogs-db:
    image: sameersbn/postgresql
    ports:
    - "5432:5432"
    restart: always
    volumes:
      - type: bind
        source: /opt/gogs-git/db
        target: /var/lib/postgresql
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    networks:
    - git
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  git: